name: faviconfinder
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  favicon: ^1.1.2
  internet_connection_checker: ^1.0.0+1


dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
